controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

diff_drive_controller:
  ros__parameters:

    publish_rate: 10.0

    odom_frame_id: odom
    base_frame_id: base_footprint

    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]
    wheel_separation: 0.287
    wheel_radius: 0.033

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    # Whether the input has a time stamp or not
    use_stamped_vel: false
    
    # Odometry fused with IMU is published by robot_localization, so no need to publish a TF
    # based on encoders alone (https://wiki.ros.org/diff_drive_controller)
    enable_odom_tf: false

    #===========================================================================================
    open_loop: true
    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

imu_broadcaster:
  ros__parameters:

    sensor_name: mpu6050
    frame_id: imu_link
   
   # 500 data points used to calculated covariances
    static_covariance_orientation: [1.8082e-06, 0.0, 0.0, 2.12629e-06, 0.0, 0.0, 4.25058e-08, 0.0, 0.0]
    static_covariance_angular_velocity: [2.64598e-07, 0.0, 0.0, 4.76816e-07, 0.0, 0.0, 3.38328e-07, 0.0, 0.0]
    static_covariance_linear_acceleration: [0.000201056, 0.0, 0.0, 0.000187677, 0.0, 0.0, 0.00050001, 0.0, 0.0]

